# Generated by Django 5.2.7 on 2025-10-16 14:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('contenido', wagtail.fields.StreamField([('parrafo', 0), ('codigo', 3), ('imagen', 4), ('alerta', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Contenido de texto enriquecido', 'label': 'Párrafo'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Lenguaje de programación (ej: python, javascript)', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Código fuente'}), 3: ('wagtail.blocks.StructBlock', [[('lenguaje', 1), ('codigo', 2)]], {'label': 'Bloque de código'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen ilustrativa', 'label': 'Imagen'}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')]}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('tipo', 5), ('titulo', 6), ('contenido', 7)]], {'label': 'Alerta'})})),
            ],
            options={
                'verbose_name': 'Artículo',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ManualHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introducción principal del manual')),
            ],
            options={
                'verbose_name': 'Página Principal del Manual',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SeccionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descripcion', wagtail.fields.RichTextField(blank=True, help_text='Descripción de la sección')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono (ej: fa-book, fa-settings)', max_length=50)),
            ],
            options={
                'verbose_name': 'Sección',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SubseccionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('descripcion', wagtail.fields.RichTextField(blank=True, help_text='Descripción de la subsección')),
            ],
            options={
                'verbose_name': 'Subsección',
            },
            bases=('wagtailcore.page',),
        ),
    ]
