# Generated by Django 5.2.7 on 2025-10-16 14:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulopage',
            name='imagen_destacada',
            field=models.ForeignKey(blank=True, help_text='Imagen destacada del artículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='manualhomepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Imagen principal del manual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='seccionpage',
            name='imagen_seccion',
            field=models.ForeignKey(blank=True, help_text='Imagen representativa de la sección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='subseccionpage',
            name='imagen_subseccion',
            field=models.ForeignKey(blank=True, help_text='Imagen representativa de la subsección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='articulopage',
            name='contenido',
            field=wagtail.fields.StreamField([('parrafo', 0), ('codigo', 3), ('imagen', 4), ('galeria', 6), ('imagen_con_texto', 9), ('alerta', 12)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Contenido de texto enriquecido', 'label': 'Párrafo'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Lenguaje de programación (ej: python, javascript)', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Código fuente'}), 3: ('wagtail.blocks.StructBlock', [[('lenguaje', 1), ('codigo', 2)]], {'label': 'Bloque de código'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Imagen ilustrativa', 'label': 'Imagen'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Múltiples imágenes en una galería', 'label': 'Galería de imágenes'}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Izquierda'), ('right', 'Derecha'), ('center', 'Centro')]}), 8: ('wagtail.blocks.RichTextBlock', (), {}), 9: ('wagtail.blocks.StructBlock', [[('imagen', 5), ('posicion', 7), ('texto', 8)]], {'help_text': 'Imagen acompañada de texto', 'label': 'Imagen con texto'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')]}), 11: ('wagtail.blocks.CharBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('tipo', 10), ('titulo', 11), ('contenido', 8)]], {'label': 'Alerta'})}),
        ),
    ]
